library(tidyr)
library(dplyr)
setwd("/Users/tejenson/Documents/coding/R coding/livejournalText")
lj1 <- read.csv("tin_lizzy-2003-12.csv")
lj2 <- read.csv("tin_lizzy-2004-1.csv")
lj3 <- read.csv("tin_lizzy-2004-2.csv")
lj4<- read.csv("tin_lizzy-2004-3.csv")
lj5 <- read.csv("tin_lizzy-2004-4.csv")
lj6 <- read.csv("tin_lizzy-2004-5.csv")
lj7 <- read.csv("tin_lizzy-2004-6.csv")
lj8 <- read.csv("tin_lizzy-2004-7.csv")
lj9 <- read.csv("tin_lizzy-2004-8.csv")
lj10 <- read.csv("tin_lizzy-2004-9.csv")
lj11 <- read.csv("tin_lizzy-2004-10.csv")
lj12 <- read.csv("tin_lizzy-2004-11.csv")
lj13 <- read.csv("tin_lizzy-2004-12.csv")
lj14 <- read.csv("tin_lizzy-2005-1.csv")
lj15 <- read.csv("tin_lizzy-2005-2.csv")
lj16 <- read.csv("tin_lizzy-2005-3.csv")
lj17 <- read.csv("tin_lizzy-2005-4.csv")
lj18 <- read.csv("tin_lizzy-2005-5.csv")
lj19 <- read.csv("tin_lizzy-2005-6.csv")
lj20 <- read.csv("tin_lizzy-2005-7.csv")
lj21 <- read.csv("tin_lizzy-2005-8.csv")
lj22 <- read.csv("tin_lizzy-2005-9.csv")
lj23 <- read.csv("tin_lizzy-2005-10.csv")
lj24 <- read.csv("tin_lizzy-2005-11.csv")
lj25 <- read.csv("tin_lizzy-2005-12.csv")
lj26 <- read.csv("tin_lizzy-2006-1.csv")
lj27 <- read.csv("tin_lizzy-2006-2.csv")
lj28 <- read.csv("tin_lizzy-2006-3.csv")
lj29 <- read.csv("tin_lizzy-2006-4.csv")
lj30 <- read.csv("tin_lizzy-2006-5.csv")
lj31 <- read.csv("tin_lizzy-2006-6.csv")
lj32 <- read.csv("tin_lizzy-2006-7.csv")
lj33 <- read.csv("tin_lizzy-2006-8.csv")
lj34 <- read.csv("tin_lizzy-2006-9.csv")
lj35 <- read.csv("tin_lizzy-2006-10.csv")
lj36 <- read.csv("tin_lizzy-2006-11.csv")
lj37 <- read.csv("tin_lizzy-2006-12.csv")
lj38 <- read.csv("tin_lizzy-2007-1.csv")
lj39 <- read.csv("tin_lizzy-2007-2.csv")
lj40 <- read.csv("tin_lizzy-2007-3.csv")
lj41 <- read.csv("tin_lizzy-2007-4.csv")
lj42 <- read.csv("tin_lizzy-2007-5.csv")
lj43 <- read.csv("tin_lizzy-2007-6.csv")
lj44 <- read.csv("tin_lizzy-2007-7.csv")
lj45 <- read.csv("tin_lizzy-2007-8.csv")
lj46 <- read.csv("tin_lizzy-2007-9.csv")
lj47 <- read.csv("tin_lizzy-2007-10.csv")
lj48 <- read.csv("tin_lizzy-2007-11.csv")
lj49 <- read.csv("tin_lizzy-2007-12.csv")
lj50 <- read.csv("tin_lizzy-2008-1.csv")
lj51 <- read.csv("tin_lizzy-2008-2.csv")
lj52 <- read.csv("tin_lizzy-2008-3.csv")
lj53 <- read.csv("tin_lizzy-2008-4.csv")
lj54 <- read.csv("tin_lizzy-2008-5.csv")
lj55 <- read.csv("tin_lizzy-2008-6.csv")
lj56 <- read.csv("tin_lizzy-2008-7.csv")
lj57 <- read.csv("tin_lizzy-2008-8.csv")
lj58 <- read.csv("tin_lizzy-2008-9.csv")
lj59 <- read.csv("tin_lizzy-2008-10.csv")
lj60 <- read.csv("tin_lizzy-2008-11.csv")
lj61 <- read.csv("tin_lizzy-2008-12.csv")
lj62 <- read.csv("tin_lizzy-2009-1.csv")
lj63 <- read.csv("tin_lizzy-2009-2.csv")
lj64<- read.csv("tin_lizzy-2009-3.csv")
lj65 <- read.csv("tin_lizzy-2009-4.csv")
lj66 <- read.csv("tin_lizzy-2009-5.csv")
lj67 <- read.csv("tin_lizzy-2009-6.csv")
lj68 <- read.csv("tin_lizzy-2009-7.csv")
lj69 <- read.csv("tin_lizzy-2009-8.csv")
lj70 <- read.csv("tin_lizzy-2009-9.csv")
lj71 <- read.csv("tin_lizzy-2009-10.csv")
lj72 <- read.csv("tin_lizzy-2009-11.csv")
lj73 <- read.csv("tin_lizzy-2009-12.csv")
lj74 <- read.csv("tin_lizzy-2010-1.csv")
lj75 <- read.csv("tin_lizzy-2010-2.csv")
lj76 <- read.csv("tin_lizzy-2010-3.csv")
lj77 <- read.csv("tin_lizzy-2010-4.csv")
lj78 <- read.csv("tin_lizzy-2010-5.csv")
lj79 <- read.csv("tin_lizzy-2010-6.csv")

View(lj1)
bind_rows(lj1,lj2)
lj_combined <- bind_rows(lj1,lj2)
View(lj_combined)
lj_combined <- bind_rows(lj_combined,lj3)
lj_combined <- bind_rows(lj_combined,lj4)
lj_combined <- bind_rows(lj_combined,lj5)
lj_combined <- bind_rows(lj_combined,lj6)
lj_combined <- bind_rows(lj_combined,lj7)
lj_combined <- bind_rows(lj_combined,lj8)
lj_combined <- bind_rows(lj_combined,lj9)
lj_combined <- bind_rows(lj_combined,lj10)
lj_combined <- bind_rows(lj_combined,lj11)
lj_combined <- bind_rows(lj_combined,lj12)
lj_combined <- bind_rows(lj_combined,lj13)
lj_combined <- bind_rows(lj_combined,lj14)
lj_combined <- bind_rows(lj_combined,lj15)
lj_combined <- bind_rows(lj_combined,lj16)
lj_combined <- bind_rows(lj_combined,lj17)
lj_combined <- bind_rows(lj_combined,lj18)
lj_combined <- bind_rows(lj_combined,lj19)
lj_combined <- bind_rows(lj_combined,lj20)
lj_combined <- bind_rows(lj_combined,lj21)
lj_combined <- bind_rows(lj_combined,lj22)
lj_combined <- bind_rows(lj_combined,lj23)
lj_combined <- bind_rows(lj_combined,lj24)
lj_combined <- bind_rows(lj_combined,lj25)
lj_combined <- bind_rows(lj_combined,lj26)
lj_combined <- bind_rows(lj_combined,lj27)
lj_combined <- bind_rows(lj_combined,lj28)
lj_combined <- bind_rows(lj_combined,lj29)
lj_combined <- bind_rows(lj_combined,lj30)
lj_combined <- bind_rows(lj_combined,lj31)
lj_combined <- bind_rows(lj_combined,lj32)
lj_combined <- bind_rows(lj_combined,lj33)
lj_combined <- bind_rows(lj_combined,lj34)
lj_combined <- bind_rows(lj_combined,lj35)
lj_combined <- bind_rows(lj_combined,lj36)
lj_combined <- bind_rows(lj_combined,lj37)
lj_combined <- bind_rows(lj_combined,lj38)
lj_combined <- bind_rows(lj_combined,lj39)
lj_combined <- bind_rows(lj_combined,lj40)
lj_combined <- bind_rows(lj_combined,lj41)
lj_combined <- bind_rows(lj_combined,lj42)
lj_combined <- bind_rows(lj_combined,lj43)
lj_combined <- bind_rows(lj_combined,lj44)
lj_combined <- bind_rows(lj_combined,lj45)
lj_combined <- bind_rows(lj_combined,lj46)
lj_combined <- bind_rows(lj_combined,lj47)
lj_combined <- bind_rows(lj_combined,lj48)
lj_combined <- bind_rows(lj_combined,lj49)
lj_combined <- bind_rows(lj_combined,lj50)
lj_combined <- bind_rows(lj_combined,lj51)
lj_combined <- bind_rows(lj_combined,lj52)
lj_combined <- bind_rows(lj_combined,lj53)
lj_combined <- bind_rows(lj_combined,lj54)
lj_combined <- bind_rows(lj_combined,lj55)
lj_combined <- bind_rows(lj_combined,lj56)
lj_combined <- bind_rows(lj_combined,lj57)
lj_combined <- bind_rows(lj_combined,lj58)
lj_combined <- bind_rows(lj_combined,lj59)
lj_combined <- bind_rows(lj_combined,lj60)
lj_combined <- bind_rows(lj_combined,lj61)
lj_combined <- bind_rows(lj_combined,lj62)
lj_combined <- bind_rows(lj_combined,lj63)
lj_combined <- bind_rows(lj_combined,lj64)
lj_combined <- bind_rows(lj_combined,lj65)
lj_combined <- bind_rows(lj_combined,lj66)
lj_combined <- bind_rows(lj_combined,lj67)
lj_combined <- bind_rows(lj_combined,lj68)
lj_combined <- bind_rows(lj_combined,lj69)
lj_combined <- bind_rows(lj_combined,lj70)
lj_combined <- bind_rows(lj_combined,lj71)
lj_combined <- bind_rows(lj_combined,lj72)
lj_combined <- bind_rows(lj_combined,lj73)
lj_combined <- bind_rows(lj_combined,lj74)
lj_combined <- bind_rows(lj_combined,lj75)
lj_combined <- bind_rows(lj_combined,lj76)
lj_combined <- bind_rows(lj_combined,lj77)
lj_combined <- bind_rows(lj_combined,lj78)
lj_combined <- bind_rows(lj_combined,lj79)
length(lj_combined)
# keep eventtime, subject & event
lj_keep <- subset(lj_combined, select = -c(itemid, logtime, security, allowmask, current_music, current_mood))
head(lj_keep)
View(lj_keep)
write.table(lj_keep, "lj_keep.txt", sep="\t")
lj_keep$newdate <- strptime(as.character(lj_keep$eventtime), "%Y-%m-%d")
lj_keep2 <- subset(lj_keep, select = -c(eventtime))
View(lj_keep2)
# reorder columns in the order I prefer them
lj_keep2 <-lj_keep2[,c(3,1,2)]
# kick to textfile
write.table(lj_keep2, "lj_keep.txt", sep="\t")

